#!/usr/bin/env bash
# This script prints "Best school" 10 times and "hi" on line 9

count=0
while [ $count -lt 10 ]
do
    echo "Best School"
    ((count++))
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
done
