#!/usr/bin/env bash
# Print best school 10 times, "bad luck" for the 4th loop iteration && "good luck" for 8th
count=1

while [ $count -le 10 ]
do
    if [ $count -eq 4 ]
    then
        echo "bad luck"
    elif [ $count -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((count++))
done

