#!/usr/bin/env bash
# Print 1 to 20, displays bad luck from China for the 4th loop , bad luck from Japan for the 9th bad luck from Italy for the 17th

n=1

while [ $n -le 20 ]
do
    echo $n
    case $n in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            ;;
    esac
    ((n++))
done
