#!/usr/bin/env bash
# displays information about the School file

fileN="School"

if [ -e $fileN ]
then
    echo "School file exists"
    if [ -s $fileN ]
    then
        echo "School file is not empty"
    else
        echo "School file is empty"
    fi
    if [ -f $fileN ]
    then
        echo "School is a regular file"
    fi
else
    echo "School file does not exist"
fi
